fixtures:
    symlinks:
      classroom: "#{source_dir}"
    forge_modules:
      windows_env: "badgerious/windows_env"
      chocolatey: "chocolatey/chocolatey"
      graphite: "dwerder/graphite"
      grafana: "dwerder/grafana"
      docker: "garethr/docker"
      wordpress: "hunner/wordpress"
      irc: "jamtur01/irc"
      fileshare: "jordan/fileshare"
      windows_ad: "jriviere/windows_ad"
      download_file: "puppet/download_file"
      windowsfeature: "puppet/windowsfeature"
      dirtree: "pltraining/dirtree"
      rbac: "pltraining/rbac"
      userprefs: "pltraining/userprefs"
      acl: "puppetlabs/acl"
      apache: "puppetlabs/apache"
      concat:
        repo: "puppetlabs/concat"
        ref: '1.2.4'
      git: "puppetlabs/git"
      haproxy: "puppetlabs/haproxy"
      inifile: "puppetlabs/inifile"
      mysql: "puppetlabs/mysql"
      ntp: "puppetlabs/ntp"
      pe_puppetserver_gem: "puppetlabs/pe_puppetserver_gem"
      puppetserver_gem: "puppetlabs/puppetserver_gem"
      reboot: "puppetlabs/reboot"
      registry: "puppetlabs/registry"
      stdlib: "puppetlabs/stdlib"
      vcsrepo: "puppetlabs/vcsrepo"
      epel: "stahnma/epel"
      exports: "zack/exports"
      r10k: "zack/r10k"
      ruby: "puppetlabs/ruby"
      gcc: "puppetlabs/gcc"
      pe_gem: "puppetlabs/pe_gem"
      make: "croddy/make"
      portage: "gentoo/portage"