fixtures:
  repositories:
    dirtree: "git://github.com/puppetlabs/pltraining-dirtree.git"
    dockeragent: "git://github.com/puppetlabs/pltraining-dockeragent.git"
    rbac: "git://github.com/puppetlabs/pltraining-rbac.git"
    userprefs: "git://github.com/puppetlabs/pltraining-userprefs.git"
    pe_repo: "git@github.com:puppetlabs/puppetlabs-pe_repo.git"
  forge_modules:
    abalone: "binford2k/abalone"
    firewall: "puppetlabs/firewall"
    chocolatey: "chocolatey/chocolatey"
    graphite: 
      repo: "dwerder/graphite"
      ref: "5.16.1"
    grafana: "dwerder/grafana"
    docker: "garethr/docker"
    wordpress: "hunner/wordpress"
    irc: "jamtur01/irc"
    fileshare: "jordan/fileshare"
    apache: "puppetlabs/apache"
    concat: "puppetlabs/concat"
    git: "puppetlabs/git"
    haproxy: "puppetlabs/haproxy"
    inifile: "puppetlabs/inifile"
    mysql: "puppetlabs/mysql"
    ntp: 
      repo: "puppetlabs/ntp"
      ref: "4.2.0"
    pe_puppetserver_gem: "puppetlabs/pe_puppetserver_gem"
    puppet_enterprise: "geoffwilliams/puppet_enterprise"
    puppetserver_gem: "puppetlabs/puppetserver_gem"
    puppetfactory: "pltraining/puppetfactory"
    stdlib: "puppetlabs/stdlib"
    vcsrepo: "puppetlabs/vcsrepo"
    windows: "puppetlabs/windows"
    epel: "stahnma/epel"
    exports: "zack/exports"
    r10k: "zack/r10k"
    stunnel: "arusso/stunnel"
    staging: "puppet/staging"
    sysctl: "fiddyspence/sysctl"
    ssh: "attachmentgenie/ssh"
    showoff: "pltraining/showoff"
  symlinks:
    classroom: "#{source_dir}"
