#! /bin/sh

# If we don't have a HEAD, then this is the first commit and we can't do any of this
git show > /dev/null 2>&1
if [ $? -ne 0 ]; then exit 0; fi

# Manually stash working changes
git diff --binary > /tmp/stash.$$

if [[ -s /tmp/stash.$$ ]]
then
  STASH_EXISTS=true
else
  STASH_EXISTS=false
fi

EXITCODE=0
for file in `git diff-index --cached --diff-filter=AM --name-only HEAD`
do
  echo "Validating ${file}..."

  case "${file##*.}" in
    "pp")  puppet parser validate ${file}
           ;;

    "erb") /opt/puppet/bin/erb -P -x -T '-' ${file} | /opt/puppet/bin/ruby -c >/dev/null
           ;;

    "yaml") /opt/puppet/bin/ruby -ryaml -e "YAML.load_file '${file}'" >/dev/null
           ;;

  esac

  EXITCODE=$((EXITCODE + $?))
done

if [ $EXITCODE -ne 0 ]
then
  echo
  echo "################################################################"
  echo -e "### \033[31mPlease fix the errors above before committing your code.\033[0m ###"
  echo "################################################################"
  if $STASH_EXISTS
  then
    echo "###                                                          ###"
    echo -e "###     \033[31mDid you remember to git add your updated code?\033[0m       ###"
    echo "###                                                          ###"
    echo "################################################################"
  fi
  echo
fi

# Now recover the working files
if $STASH_EXISTS
then
  git apply --whitespace=nowarn < /tmp/stash.$$
  rm /tmp/stash.$$
fi

exit $EXITCODE

