# Builds a basic Centos<%= $os_major %> container with pe-agent installed
# This image is for training purposes and is not intended for production environments.
FROM centos:<%= $os_major %> 
MAINTAINER Josh Samuelson <js@puppetlabs.com>
ENV HOME /root/
ENV TERM xterm
ENV PATH /usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/opt/puppetlabs/puppet/bin
RUN yum -y install  tar dmidecode which logrotate cyrus-sasl libxslt cronie pciutils git rubygems vim tree csh zsh net-tools wget
RUN gem install multipart-post -v 1.2.0
RUN rpm -Uvh https://yum.puppetlabs.com/puppetlabs-release-pc1-el-<%= $os_major %>.noarch.rpm
RUN yum -y install puppet-agent
ADD puppet.conf /etc/puppetlabs/puppet/puppet.conf
RUN rm /etc/yum.repos.d/CentOS*
ADD base_local.repo /etc/yum.repos.d/base_local.repo
ADD epel_local.repo /etc/yum.repos.d/epel_local.repo
ADD updates_local.repo /etc/yum.repos.d/updates_local.repo
RUN yum clean all
